{application,lager_test,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[lager_test]},
              {mod,{lager_test_app,[]}},
              {applications,[kernel,stdlib,lager]},
              {env,[]},
              {modules,[lager_test,lager_test_app,lager_test_sup]},
              {maintainers,[]},
              {licenses,[]},
              {links,[]}]}.
